### ISSUE TITLE
Windows path resolving issues

### ISSUE THREAD

**Issue by ddwreczycki** [fast-data-transfer/fdt#34]
Hello there,
I'm currently trying to figure out how to use Fast Data Transfer and I did encounter an error which prevents me from using library. I will provide an exact command I'm executing with no luck.

java -jar fdt-0.26.1-SNAPSHOT.jar -pull -r -c 192.168.1.04 -d C:/Users/dev/Desktop/ /Users/danny/NetBeansProjects/fdt/target/fdt.jar — from Mac to Windows and its working perfectly fine. File is being transferred.

But in reverse order,
java -jar fdt-0.26.1-SNAPSHOT.jar -pull -r -c 192.168.105 -d /Users/danny/desktop/ C:/Users/dev/Desktop/fdt.jar  — from Windows to Mac FDT is always prompting an error.

Caused by: java.lang.IllegalArgumentException: Illegal syntax! You can use either Client/Server (-c/-d) syntax, either SCP syntax.

I'm doing something wrong? Is there syntax to format windows path to be accepted as last parameter? 

I will appreciate any informations regarding my issue.

**Comment by ddwreczycki** [comment]
Okey I made quick dive into code and spotted an issue. Its line 486 in Utils.java. There is check if path contains ':' and then if (File.separatorChar == '\\') {// "Windowns" baby!. I think checking File.separatorChar is not necessary there since its preventing from parsing windows formatted path in unix like system.

**Comment by xpan1** [comment]
Hey, how did you solve the problem eventually? I have the same problem....

**Comment by ddwreczycki** [comment]
> Hey, how did you solve the problem eventually? I have the same problem....

If I remeber correctly I just removed mentioned if statment and builded project myself.

**Comment by xpan1** [comment]
So you mean you edited the fdt directly?
