### ISSUE TITLE
scp recursive

### ISSUE THREAD

**Issue by umasstr** [fast-data-transfer/fdt#44]
This is a very fast and easy-to-use tool for transfer of individual files. Is there an "scp -r" like function that allows recursive transfer of files and dirs? I get the below error (example):

java.lang.Exception: java.io.IOException: The specified name [ FVB_liver/mus_musculus ] is not a file!

Thanks for the help!

**Comment by fixy** [comment]
Hello it has simmilar function. Please take a look in our demo page: https://fast-data-transfer.github.io/internet2-demo.html
