### ISSUE TITLE
Documentation does not specify supported Version of Java or OS

### ISSUE THREAD

**Issue by Elyasin** [fast-data-transfer/fdt#56]
I am using a Mac. The FDT is a program written in Java. I presumed that it would compile on a Mac. Unfortunately it does not.

I executed the build-all.sh script. The Java version on my system is that of the OpenJDK 15.0.1.
The error message is

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project fdt: Compilation failure
[ERROR] /Users/myname/fdt/src/edu/caltech/hep/dcapj/io/dCacheFileOutputStream.java:[74,22] error: unreported exception Throwable; must be caught or declared to be thrown
```

I am not sure if there is a bug or if my system is simply not supported.

**Comment by mcalderaro** [comment]
Can you try to use an older version of jdk and report back your findings. 

Inviato dal mio iPhone 

On May 21, 2021, at 2:21 PM, Ely ***@***.***> wrote:

﻿
I am using a Mac. The FDT is a program written in Java. I presumed that it would compile on a Mac. Unfortunately it does not.

I executed the build-all.sh script. The Java version on my system is that of the OpenJDK 15.0.1.
The error message is

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project fdt: Compilation failure
[ERROR] /Users/Elyas/fdt/src/edu/caltech/hep/dcapj/io/dCacheFileOutputStream.java:[74,22] error: unreported exception Throwable; must be caught or declared to be thrown
I am not sure if there is a bug or if my system is simply not supported.

**Comment by Elyasin** [comment]
I did so. 

I installed the OpenJDK 8.
It failed saying it can't find rpm.
I installed that on the Mac. 
I'm testing right now.  So far it looks good.

**Comment by Elyasin** [comment]
It works fine. It seems that the version of Java 8 is a suitable choice, I use OpenJDK 8.
The script does not take into account a Mac system. Though this does not seem to be a problem.
Maven can be installed manually (that is what the script does) or with brew.
With brew one can also install the rpm software that is needed, without it it won't compile.

I transferred 100 GB and the speed is about the best I can expect considering my internet provider.
